version: '3'
services:
  
  arbitrage-detector:
    container_name: arbitrage-detector
    build:
      context: .
      dockerfile: ArbitrageDetector_Dockerfile
    image: cryptobot/arbitrage-detector-image:latest
    ports:
      - "3000:80"
  
  poller-gdax-eth-eur:
    container_name: poller-gdax-eth-eur
    depends_on:
      - arbitrage-detector
    build:
      context: .
      dockerfile: PricePoller_Dockerfile
    image: cryptobot/price-poller-image:latest
    environment:
      - MARKET=GDAX
      - FROM_CURRENCY=ETH
      - TO_CURRENCY=EUR
      - PUSH_URL=http://arbitrage-detector:80/api/price
  
  poller-gdax-btc-eur:
    container_name: poller-gdax-btc-eur
    depends_on:
      - arbitrage-detector
    build:
      context: .
      dockerfile: PricePoller_Dockerfile
    image: cryptobot/price-poller-image:latest
    environment:
      - MARKET=GDAX
      - FROM_CURRENCY=BTC
      - TO_CURRENCY=EUR
      - PUSH_URL=http://arbitrage-detector:80/api/price

  poller-gdax-bch-eur:
    container_name: poller-gdax-bch-eur
    depends_on:
      - arbitrage-detector
    build:
      context: .
      dockerfile: PricePoller_Dockerfile
    image: cryptobot/price-poller-image:latest
    environment:
      - MARKET=GDAX
      - FROM_CURRENCY=BCH
      - TO_CURRENCY=EUR
      - PUSH_URL=http://arbitrage-detector:80/api/price
  
  poller-coinbase-eth-eur:
    container_name: poller-coinbase-eth-eur
    depends_on:
      - arbitrage-detector
    build:
      context: .
      dockerfile: PricePoller_Dockerfile
    image: cryptobot/price-poller-image:latest
    environment:
      - MARKET=Coinbase
      - FROM_CURRENCY=ETH
      - TO_CURRENCY=EUR
      - PUSH_URL=http://arbitrage-detector:80/api/price

  poller-coinbase-btc-eur:
    container_name: poller-coinbase-btc-eur
    depends_on:
      - arbitrage-detector
    build:
      context: .
      dockerfile: PricePoller_Dockerfile
    image: cryptobot/price-poller-image:latest
    environment:
      - MARKET=Coinbase
      - FROM_CURRENCY=BTC
      - TO_CURRENCY=EUR
      - PUSH_URL=http://arbitrage-detector:80/api/price

  poller-coinbase-bch-eur:
    container_name: poller-coinbase-bch-eur
    depends_on:
      - arbitrage-detector
    build:
      context: .
      dockerfile: PricePoller_Dockerfile
    image: cryptobot/price-poller-image:latest
    environment:
      - MARKET=Coinbase
      - FROM_CURRENCY=BCH
      - TO_CURRENCY=EUR
      - PUSH_URL=http://arbitrage-detector:80/api/price

  poller-kraken-eth-eur:
    container_name: poller-kraken-eth-eur
    depends_on:
      - arbitrage-detector
    build:
      context: .
      dockerfile: PricePoller_Dockerfile
    image: cryptobot/price-poller-image:latest
    environment:
      - MARKET=Kraken
      - FROM_CURRENCY=ETH
      - TO_CURRENCY=EUR
      - PUSH_URL=http://arbitrage-detector:80/api/price

  poller-kraken-btc-eur:
    container_name: poller-kraken-btc-eur
    depends_on:
      - arbitrage-detector
    build:
      context: .
      dockerfile: PricePoller_Dockerfile
    image: cryptobot/price-poller-image:latest
    environment:
      - MARKET=Kraken
      - FROM_CURRENCY=BTC
      - TO_CURRENCY=EUR
      - PUSH_URL=http://arbitrage-detector:80/api/price

  poller-kraken-bch-eur:
    container_name: poller-kraken-bch-eur
    depends_on:
      - arbitrage-detector
    build:
      context: .
      dockerfile: PricePoller_Dockerfile
    image: cryptobot/price-poller-image:latest
    environment:
      - MARKET=Kraken
      - FROM_CURRENCY=BCH
      - TO_CURRENCY=EUR
      - PUSH_URL=http://arbitrage-detector:80/api/price